version: '3'

services:

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '127.0.0.1:27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - .local/data:/data/mesa
    logging:
      driver: none


volumes:
  data:
  # pgdata:
  node_modules:
